lib/treelib_web/router.ex
defmodule TreelibWeb.Router do
  use TreelibWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TreelibWeb.CurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TreelibWeb do
    pipe_through(:browser)

    get("/", PageController, :home)
    get("/about", PageController, :about)
    get("/contact", PageController, :contact)

    get("/search", SearchController, :index)

    get("/register", RegistrationController, :new)
    post("/register", RegistrationController, :create)

    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    delete("/logout", SessionController, :delete)

    resources("/family", FamilyController, except: [:index, :show])
    get("/family.json", FamilyController, :index)
    get("/family/:id/:name", FamilyController, :show)
    get("/family/:id", FamilyController, :show)

    resources("/genus", GenusController, except: [:index, :show])
    get("/genus/:id/:name", GenusController, :show)
    get("/genus/:id", GenusController, :show)

    resources("/species", SpeciesController, except: [:show])
    get("/species.json", SpeciesController, :index_json)
    get("/species/:id/:name", SpeciesController, :show)
    get("/species/:id", SpeciesController, :show)

    get("/photo_album.json", PhotoAlbumController, :index)

    get("/contributors", ContributorController, :index)

    get("/qr/:id", QrController, :show)
    post("/qr", QrController, :create)
  end

  scope "/", TreelibWeb do
    get("/sitemap.xml", SitemapController, :sitemap)
    get("/sitemaps/sitemap.xml", SitemapController, :sitemap)
    get("/sitemaps/sitemap1.xml", SitemapController, :sitemap1)
  end

  scope "/api", TreelibWeb do
    pipe_through(:api)

    get("/photos", PhotoController, :index)
  end

  scope "/admin", TreelibWeb do
    pipe_through(:browser)

    get("/", AdminController, :index)
    get("/debug", AdminDebugController, :index)
    get("/oauth", OAuthController, :index)
    post("/oauth/access_token", OAuthController, :access_token)
    post("/refresh", AdminController, :refresh)
    resources("/contributors", AdminContributorController)

    get("/qr", AdminQrController, :index)
    resources("/url_qr", AdminUrlQrController, only: [:show, :create], singleton: true)
  end
end

lib/treelib_web/controllers/admin_qr_controller.ex
defmodule TreelibWeb.AdminQrController do
  use TreelibWeb, :controller

  @moduledoc """
  Admin Controller for qr codes
  """

  alias Treelib.QR.QrManager

  def index(conn, _params) do
    with {:ok, _current_user} <- auth_admin(conn) do
      species = QrManager.species_with_code()
      render(conn, "index.html", species: species)
    end
  end
end

lib/treelib_web/views/admin_qr_view.ex
defmodule TreelibWeb.AdminQrView do
  use TreelibWeb, :view

  alias Treelib.QR.QrManager

  def qr_code(code) do
    QrManager.qr_code_url(code)
  end

  def format_date(naive_date) do
    {:ok, date} = DateTime.from_naive(naive_date, "Etc/UTC")

    date
    |> DateTime.to_string()
  end
end

lib/treelib_web/templates/admin_qr/index.html.eex
<div id="app" class="admin">
  <div>
    <%= render TreelibWeb.AdminView, "_navbar.html", assigns %>
    <h1>
      QR Codes
    </h1>
    <div>
      <hr/>
      <p>
        Simple QR generator code for urls:
      </p>
      <%= form_for :qr_url, Routes.admin_url_qr_path(TreelibWeb.Endpoint, :create), fn f -> %>
        <%= text_input f, :url, value: "", placeholder: "url" %>
        <%= submit "Create" %>
      <% end %> 
      <hr/>
    </div>
    <table class="admin responsive" style="text-align: center;">
      <thead>
        <tr>
          <th>Species</th>
          <th>QR Code</th>
        </tr>
      </thead>
      <tbody>
        <%= for s <- @species do %>
          <tr>
            <td>
              <b>
                <a href=<%= "/species/#{s.id}/edit" %>>
                  <i><%= "#{s.genus.name} #{s.name}" %></i></br>
                  <%= "#{s.genus.common_name} #{s.common_name}" %>
                </a>
              </b>
              </br>
              </br>
              <span>
                <%= "Scans: #{s.code.count}" %>
              </span>
              </br>
              <span 
                class="date"
                data-date='<%= format_date(s.code.updated_at) %>'
                style="font-size: 1.2rem;"
              ></span>
            </td>
            <td>
              <div
                class="code"
                data-name='<%= String.replace("#{s.genus.common_name} #{s.common_name}", " ", "_") %>'
                data-url='<%= qr_code(s.code) %>'></div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<script src='<%= Routes.static_path(@conn, "/js/autres.bundle.js") %>'></script>
<script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/qrcode.min.js") %>'></script>
<script type="text/javascript">
  const codes = document.getElementsByClassName("code");
  for(let i = 0; i < codes.length; i++) {
    const qr_url = codes[i].getAttribute("data-url");
    const name = codes[i].getAttribute("data-name");

    QRCode.toDataURL(qr_url, {width: 250})
    .then(url => {
      const a = document.createElement('a');
      a.setAttribute("download", filename =  `qr_${name}.png`);
      a.setAttribute("href", url);
      a.innerHTML = "download";

      const img = document.createElement('img');
      img.src =  url;

      codes[i].appendChild(img);
      codes[i].appendChild(a);
    })
    .catch(err => {
      console.log("QR ERROR: ", err);
    });
  }
  

  const dates = document.getElementsByClassName("date");
  for(let i = 0; i < dates.length; i++) {
    const date = new Date(dates[i].getAttribute("data-date"));
    dates[i].innerHTML = `(${date.toLocaleString()})`;
  }
</script>