lib/treelib_web/router.ex
defmodule TreelibWeb.Router do
  use TreelibWeb, :router

  pipeline :browser do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:fetch_live_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TreelibWeb.CurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TreelibWeb do
    pipe_through(:browser)

    get("/", PageController, :home)
    get("/about", PageController, :about)
    get("/contact", PageController, :contact)

    get("/search", SearchController, :index)

    get("/register", RegistrationController, :new)
    post("/register", RegistrationController, :create)

    get("/login", SessionController, :new)
    post("/login", SessionController, :create)
    delete("/logout", SessionController, :delete)

    resources("/family", FamilyController, except: [:index, :show])
    get("/family.json", FamilyController, :index)
    get("/family/:id/:name", FamilyController, :show)
    get("/family/:id", FamilyController, :show)

    resources("/genus", GenusController, except: [:index, :show])
    get("/genus/:id/:name", GenusController, :show)
    get("/genus/:id", GenusController, :show)

    resources("/species", SpeciesController, except: [:show])
    get("/species.json", SpeciesController, :index_json)
    get("/species/:id/:name", SpeciesController, :show)
    get("/species/:id", SpeciesController, :show)

    get("/photo_album.json", PhotoAlbumController, :index)

    get("/contributors", ContributorController, :index)

    get("/qr/:id", QrController, :show)
    post("/qr", QrController, :create)
  end

  scope "/", TreelibWeb do
    get("/sitemap.xml", SitemapController, :sitemap)
    get("/sitemaps/sitemap.xml", SitemapController, :sitemap)
    get("/sitemaps/sitemap1.xml", SitemapController, :sitemap1)
  end

  scope "/api", TreelibWeb do
    pipe_through(:api)

    get("/photos", PhotoController, :index)
  end

  scope "/admin", TreelibWeb do
    pipe_through(:browser)

    get("/", AdminController, :index)
    get("/debug", AdminDebugController, :index)
    get("/oauth", OAuthController, :index)
    post("/oauth/access_token", OAuthController, :access_token)
    post("/refresh", AdminController, :refresh)
    resources("/contributors", AdminContributorController)

    get("/qr", AdminQrController, :index)
    resources("/url_qr", AdminUrlQrController, only: [:show, :create], singleton: true)
  end
end

lib/treelib_web/controllers/admin_contributor_controller.ex
defmodule TreelibWeb.AdminContributorController do
  use TreelibWeb, :controller

  alias Treelib.Contributions
  alias Treelib.Contributions.Contributor

  action_fallback AdminFallbackController

  def index(conn, _params) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributors = Contributions.list_contributors()
      render(conn, "index.html", contributors: contributors)
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def new(conn, _params) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributor =
        %Contributor{}
        |> Treelib.Repo.preload([species: [:genus]])

      changeset = Contributions.change_contributor(contributor)
      render(conn, "new.html", contributor: contributor, changeset: changeset)
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def create(conn, %{"contributor" => contributor_params}) do
    with {:ok, _current_user} <- auth_admin(conn) do
      case Contributions.create_contributor(contributor_params) do
        {:ok, _contributor} ->
          conn
          |> put_flash(:info, "Contributor created successfully.")
          |> redirect(to: Routes.admin_contributor_path(conn, :index))

        {:error, %Ecto.Changeset{} = changeset} ->
          contributor =
            %Contributor{}
            |> Treelib.Repo.preload([species: [:genus]])
          render(conn, "new.html", contributor: contributor, changeset: changeset)
      end
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def show(conn, %{"id" => id}) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributor = Contributions.get_contributor!(id)
      render(conn, "show.html", contributor: contributor)
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def edit(conn, %{"id" => id}) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributor = Contributions.get_contributor!(id)
      changeset   = Contributions.change_contributor(contributor)

      render(conn, "edit.html", contributor: contributor, changeset: changeset)
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def update(conn, %{"id" => id, "contributor" => contributor_params}) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributor = Contributions.get_contributor!(id)

      contributor_params = maybe_set_empty_species(contributor_params)

      case Contributions.update_contributor(contributor, contributor_params) do
        {:ok, contributor} ->
          conn
          |> put_flash(:info, "Contributor updated successfully.")
          |> redirect(to: Routes.admin_contributor_path(conn, :show, contributor))

        {:error, %Ecto.Changeset{} = changeset} ->
          contributor = contributor |> Treelib.Repo.preload(:species)
          render(conn, "edit.html", contributor: contributor, changeset: changeset)
      end
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  def delete(conn, %{"id" => id}) do
    with {:ok, _current_user} <- auth_admin(conn) do
      contributor = Contributions.get_contributor!(id)
      {:ok, _contributor} = Contributions.delete_contributor(contributor)

      conn
      |> put_flash(:info, "Contributor deleted successfully.")
      |> redirect(to: Routes.admin_contributor_path(conn, :index))
    else
      {:error, _ } -> redirect conn, to: Routes.search_path(conn, :index)
    end
  end

  defp maybe_set_empty_species(%{"species_ids" => _ } = params), do: params

  # If no species_ids are passed, assume the user has removed
  # any associated species from the contributor
  defp maybe_set_empty_species params do
    params
    |> Map.put("species_ids", [])
  end

end

lib/treelib_web/views/admin_contributor_view.ex
defmodule TreelibWeb.AdminContributorView do
  use TreelibWeb, :view

  alias Treelib.Taxonomy

  defp formatted_species_list do
    Taxonomy.get_species_list()
    |> Enum.map(fn s ->
      {"#{s[:genus_name]} #{s[:name]}", s[:id]}
    end)
  end
end

lib/treelib_web/templates/admin_contributor/edit.html.eex
<div id="app" class="admin">
  <div>
    <%= render TreelibWeb.AdminView, "_navbar.html", assigns %>

    <h1>Edit Contributor</h1>

    <%= render "form.html", Map.put(assigns, :action, Routes.admin_contributor_path(@conn, :update, @contributor)) %>
  </div>
</div>

lib/treelib_web/templates/admin_contributor/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-basic">

    <hr/>

    <div class="form-group">
      <%= label f, :first_name, class: "control-label" %>
      <%= text_input f, :first_name %>
      <%= error_tag f, :first_name %>
    </div>

    <hr/>

    <div class="form-group">
      <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name %>
    <%= error_tag f, :last_name %>
    </div>

    <hr/>

    <div id="description" class="form-group">
      <%= label f, :description, class: "control-label" %>
      <%= error_tag f, :description %>
      <%= textarea f, :description %>
    </div>

    <hr/>

    <div class="form-group hidden">
      <%= label f, :species, class: "control-label" %>
      <%= multiple_select(f, :species_ids, formatted_species_list(), selected: Enum.map(@contributor.species, &(&1.id)), id: "species") %>
      <%= error_tag f, :species_ids %>
    </div>

    <hr/>

    <%= submit "Save", id: "saveButton", class: "button" %>
  </div>

  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/jquery-git.min.js") %>"></script>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/select2.min.js") %>"></script>
	<link href="<%= Routes.static_path(@conn, "/css/select2.min.css") %>" rel="stylesheet" />
  <script>
    $(document).ready(function() {
      $('#species').select2({
				width: '450px'
			});

      $(".form-group.hidden").show();
    });
  </script>
<% end %>

lib/treelib_web/templates/admin_contributor/index.html.eex
<div id="app" class="admin">
  <div>
    <%= render TreelibWeb.AdminView, "_navbar.html", assigns %>

    <h1>
      Contributors
      <span><%= link "New Contributor", to: Routes.admin_contributor_path(@conn, :new), class: "header-btn success"%></span>
    </h1>
    <table class="admin responsive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Species</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= for contributor <- @contributors do %>
          <tr>
            <td>
              <%= "#{contributor.first_name} #{contributor.last_name}" %>
            </td>
            <td>
              <%= contributor.description %>
            </td>
            <td>
              <ul>
              <%= for species <- contributor.species do %>
                <li><%= link "#{species.genus.name} #{species.name}", to: Routes.species_path(@conn, :edit, species) %></li>
              <% end %>
              </ul>
            </td>
            <td class="center-column">
              <%= link "Show", to: Routes.admin_contributor_path(@conn, :show, contributor), class: "action" %>
              <%= link "Edit", to: Routes.admin_contributor_path(@conn, :edit, contributor), class: "action edit" %>
              <%= link "Delete", to: Routes.admin_contributor_path(@conn, :delete, contributor), method: :delete, data: [confirm: "Are you sure?"], class: "action delete" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<script src="<%= Routes.static_path(@conn, "/js/autres.bundle.js") %>"></script>

lib/treelib_web/templates/admin_contributor/new.html.eex
<div id="app" class="admin">
  <div>
    <%= render TreelibWeb.AdminView, "_navbar.html", assigns %>

    <h1>New Contributor</h1>

    <%= render "form.html", Map.put(assigns, :action, Routes.admin_contributor_path(@conn, :create)) %>
  </div>
</div>

lib/treelib_web/templates/admin_contributor/show.html.eex
<div id="app"  class="admin">
  <div>
    <%= render TreelibWeb.AdminView, "_navbar.html", assigns %>

    <div>
      <h1>Contributor: <%= "#{@contributor.first_name} #{@contributor.last_name}" %> <span><%= link "Edit", to: Routes.admin_contributor_path(@conn, :edit, @contributor), class: "header-btn edit"%></span></h1>

      <h3>Description</h3>
      <p>
        <%= "#{@contributor.description}" %>
      </p>

      <h3>Species</h3>
      <ul>
        <%= for species <- @contributor.species do %>
          <li><%= link "#{species.genus.name} #{species.name}", to: Routes.species_path(@conn, :edit, species) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>